apiVersion: v1
data:
  VAULT_ROLE_ID: MmZjYzUxMmYtMTBjNS1jNTliLWI3YzUtNTNlNWQzNDIyZjRl
  VAULT_SECRET_ID: ZjQ3N2Q0MWQtMzMxNS0yMWVkLWY0NjQtZmUxMTUwY2U5Yjll
kind: Secret
metadata:
  name: secret-vault
  namespace: portal
type: Opaque